language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 7.1
  - 7.2

env:
    matrix:
      - PREFER_LOWEST="--prefer-lowest"
      - PREFER_LOWEST=""

matrix:
  allow_failures:
      - php: 7.2

before_script:
    - composer self-update
    - composer update $PREFER_LOWEST

script:
  - vendor/bin/phpunit
