language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 7.4

env:
    matrix:
      - PREFER_LOWEST="--prefer-lowest"
      - PREFER_LOWEST=""

install:
  - 'composer self-update'
  - 'wget https://github.com/phpstan/phpstan/releases/download/0.12.33/phpstan.phar'
  - 'php phpstan.phar --version'
  - 'wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar && mv php-cs-fixer-v2.phar php-cs-fixer.phar'
  - 'php php-cs-fixer.phar --version'
  - 'wget https://scrutinizer-ci.com/ocular.phar'

before_script:
    - composer update $PREFER_LOWEST

script:
  - 'php ./vendor/bin/phpunit'
  - 'php phpstan.phar analyse -l max src'
  - 'PHP_CS_FIXER_FUTURE_MODE=1 php php-cs-fixer.phar fix --allow-risky=yes --diff --dry-run'
  - 'php ocular.phar code-coverage:upload --format=php-clover clover.xml'
